### ISSUE TITLE
bug in "creep.setup.upgrader"

### ISSUE THREAD

**Issue by BringerOD** [cyberblast/screeps.behaviour-action-pattern#112]
It was not calculating the maxCount correctly.  This was my fix.

BTW,  awesome scripts!!

`var setup = new Creep.Setup('upgrader');
setup.multiBody = [WORK, WORK, WORK, WORK, MOVE];
setup.fixedBody = [WORK, WORK, WORK, CARRY, MOVE];
setup.minAbsEnergyAvailable = 350;
setup.maxMulti = 4;
setup.minEnergyAvailable = function(spawn){
    return 0.8;
};
setup.maxCount = function(spawn){

    let chargeables = spawn.room.chargeablesOut;
    if (spawn.room.storage)  chargeables.push(chargeables);
    if (chargeables.length > 0)
        return spawn.room.controller.pos.findInRange(chargeables, 2 ) ? 3 : 0;
        else
        return 0;

 
};
setup.maxWeight = function(spawn){
    return null;
};
module.exports = setup;`

**Comment by cyberblast** [comment]
Hi Bringer, 
thanks for the fix! :) 

Can you provide a description what the actually problem was? 
I can see some changes in your code. 
- number of upgraders increased to 3
- find in range 2, not 3
- overall formatting/layout  

which of them is the fix?  
I think the number of upgraders is a matter of taste. Personally I try to reduce creep numbers as much as possible (better bigger creeps). 
The find with range of 2 will fail in one of my rooms. 3 should be perfect for the upgrader to take seat on it while still in range to upgrade the controller. 
Has there been an error due to the formatting/code layout?

**Comment by BringerOD** [comment]
Sorry about that.  The only fix was here.

When "spawn.room.storage" did not exist it created 1.

Sorry you see a little of my customization in there.  Looks like I had an error as well.  still should be 3 distance, and 1 upgrader.

Here is the update to the section.  

`let chargeables = spawn.room.chargeablesOut;
if (spawn.room.storage)  chargeables.push(chargeables);
if (chargeables.length > 0)
    return spawn.room.controller.pos.findInRange(chargeables, 3 ) ? 1 : 0;
    else
    return 0;`

**Comment by cyberblast** [comment]
Great, 
I implemented the fix. 
Thank you :)
